server.port = 8081
ADYEN_API_KEY=AQEphmfuXNWTK0Qc+iSVhGU1t/eaSYVKDMIcCsuoWXhZrMaYlaedvagFbUkQwV1bDb7kfNy1WIxIIkxgBw==-uXmd+pjEDC3buzh6YKaTaqwM3rKlaSymiOx/pP4UCB4=-i1i[~qsF~%X,daB?[B5
ADYEN_MERCHANT_ACCOUNT=Evampsaanga162POS
ADYEN_CLIENT_KEY=test_7F6ZBKPJYBDQ3NBFVMEIPM5CLIBLLWYY
ADYEN_HMAC_KEY=6AD147C2D16467ED503D81152C13D35DBCD5DD1E509F15BDB099FF9E8B4D3BD6
