spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

server.port=8080
#ADYEN_API_KEY=AQEwhmfxKYnPYxBBw0m/n3Q5qf3VbZ1MAINZWWRYwXn6yDTu2PweESPj6t8jcXerQHk6EMFdWw2+5HzctViMSCJMYAc=-J+zbr0dsDjglieSMRHTSwhEOHnve7OO/XKSTKBTY2Qw=-i1igYNcSQ_vS8}U75F%
ADYEN_API_KEY=AQEwhmfxJ4LKaBVBw0m/n3Q5qf3VbZ1MAINZWWRYwXn6yDTzRoVNrFUszftGbi7+oeDBEMFdWw2+5HzctViMSCJMYAc=-RzzsHmPcNquEVyo4UDW6hZAovS1Jc/0JYNsn+80zitA=-i1ia,93GM]tf:s,EMsL
ADYEN_MERCHANT_ACCOUNT=Evampsaanga162ECOM
#ADYEN_CLIENT_KEY=test_5WWIT3ZSBVFKVJWRFWR265RFIYVUUPMZ
ADYEN_CLIENT_KEY=test_QY7W74VAIZAQVBELNJVDU2VHKIQEWFAR
#ADYEN_HMAC_KEY=6AD147C2D16467ED503D81152C13D35DBCD5DD1E509F15BDB099FF9E8B4D3BD6
ADYEN_HMAC_KEY=1A92D333E7A20EA433D10FCBAB7239384D1ED9805880C5741A2FB068B02AE44B
